version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Uses Amazon Corretto 17
  build:
    commands:
      - echo "Building the application using Maven..."
      - mvn clean package -DskipTests
artifacts:
  files:
    - '**/*'
