version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package
      - cp target/*.jar application.jar
artifacts:
  files:
    - application.jar